PROJECTNAME=Clearas
WIN32DIR=bin\Win32
WIN32EXE=$(WIN32DIR)\Release\$(PROJECTNAME).exe
PORTABLE32EXE=$(WIN32DIR)\Portable\$(PROJECTNAME).exe
WIN64DIR=bin\Win64
WIN64EXE=$(WIN64DIR)\Release\$(PROJECTNAME).exe
PORTABLE64EXE=$(WIN64DIR)\Portable\$(PROJECTNAME).exe

BDSDIR=C:\Program Files (x86)\Embarcadero\Studio\16.0
MSBUILD=C:\Windows\Microsoft.NET\Framework\v3.5\MSBUILD.exe
SIGNTOOL="C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe"
SIGN=$(SIGNTOOL) sign /v /n "PM Code Works" /tr http://timestamp.globalsign.com/scripts/timstamp.dll /td SHA256 /fd SHA256
INNOSETUP="C:\Program Files (x86)\Inno Setup 5\ISCC.exe"

build: win32 win64

release: clean build sign buildsetup portable signportable source

source:
	hg archive -t zip $(PROJECTNAME)-src.zip

win32: src\$(PROJECTNAME).dproj
	SET BDS=$(BDSDIR)
	IF NOT EXIST bin\Win32 MKDIR bin\Win32
	$(MSBUILD) /p:Config=Release /p:Platform=Win32 "src\$(PROJECTNAME).dproj"

win64: src\$(PROJECTNAME).dproj
	SET BDS=$(BDSDIR)
	IF NOT EXIST bin\Win64 MKDIR bin\Win64
	$(MSBUILD) /p:Config=Release /p:Platform=Win64 "src\$(PROJECTNAME).dproj"

sign: $(WIN32EXE) $(WIN64EXE)
	$(SIGN) $(WIN32EXE) $(WIN64EXE)

buildsetup: setup\$(PROJECTNAME).iss
	$(INNOSETUP) setup\$(PROJECTNAME).iss

win32portable: src\$(PROJECTNAME).dproj
	SET BDS=$(BDSDIR)
	$(MSBUILD) /p:Config=Portable /p:Platform=Win32 "src\$(PROJECTNAME).dproj"

win64portable: src\$(PROJECTNAME).dproj
	SET BDS=$(BDSDIR)
	$(MSBUILD) /p:Config=Portable /p:Platform=Win64 "src\$(PROJECTNAME).dproj"

signportable: $(PORTABLE32EXE) $(PORTABLE64EXE)
	$(SIGN) $(PORTABLE32EXE) $(PORTABLE64EXE)

portable: win32portable win64portable signportable

clean:
	SET BDS=$(BDSDIR)
	$(MSBUILD) /t:clean /p:Config=Release /p:Platform=Win32 "src\$(PROJECTNAME).dproj"
	$(MSBUILD) /t:clean /p:Config=Release /p:Platform=Win64 "src\$(PROJECTNAME).dproj"
