PROJECTNAME=Clearas
WIN32EXE=bin\Win32\$(PROJECTNAME).exe
WIN64EXE=bin\Win64\$(PROJECTNAME).exe
MSBUILD=C:\Windows\Microsoft.NET\Framework\v3.5\MSBUILD.exe
ZIP="C:\Program Files (x86)\GnuWin32\bin\zip.exe"
CERTSHA1=A9A273A222A5DD3ED9EC2F46232AAD8E087EA4ED
SIGNTOOL="C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe"
SIGN=$(SIGNTOOL) sign /v /sha1 $(CERTSHA1) /tr http://timestamp.globalsign.com/scripts/timstamp.dll /td SHA256 /fd SHA256

build: win32 win64

source: src\*.pas Makefile
	$(ZIP) -9 -r $(PROJECTNAME)-src.zip . src -x .hg\* -x tests\* -x BACKUP\* -x src\AdminManifest.rc -x TODO.txt -i MakeFile -i MakeFile.bat -i *.md -i *.txt -i *.pas -i *.dproj -i *.res -i *.rc -i *.dpr -i *.dfm -i *.inc -i *.dcr -i *.ico

win32: src\$(PROJECTNAME).dproj
	SET BDS=C:\Program Files (x86)\Embarcadero\Studio\16.0
	IF NOT EXIST bin\Win32 MKDIR bin\Win32
	$(MSBUILD) /p:Config=Release /property:Platform=Win32 "src\$(PROJECTNAME).dproj"

win64: src\$(PROJECTNAME).dproj
	SET BDS=C:\Program Files (x86)\Embarcadero\Studio\16.0
	IF NOT EXIST bin\Win64 MKDIR bin\Win64
	$(MSBUILD) /p:Config=Release /property:Platform=Win64 "src\$(PROJECTNAME).dproj"

sign: $(WIN32EXE) $(WIN64EXE)
	$(SIGN) $(WIN32EXE) $(WIN64EXE)

release: win32 win64 sign source

clean:
	IF EXIST $(WIN32EXE) DEL $(WIN32EXE)
	IF EXIST $(WIN64EXE) DEL $(WIN64EXE)
